import React, { useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { tasksApi } from '../src/services/endpoints';
import { useDayStore } from '../src/stores/useDayStore';
import { BorderRadius, Spacing, Typography } from '../src/constants/theme';
import { useAppTheme } from '../src/theme/ThemeProvider';

type ScheduleMode = 'specific' | 'prayer';
type Task = { _id: string; title: string; duration: number; anchor?: string; scheduledStart?: string };
const PRAYERS = [['after_fajr', 'بعد الفجر 🌅'], ['after_dhuhr', 'بعد الظهر 🕌'], ['before_asr', 'قبل العصر'], ['after_asr', 'بعد العصر 🌇'], ['after_maghrib', 'بعد المغرب 🌙'], ['after_isha', 'بعد العشاء ⭐'], ['before_sleep', 'قبل النوم 😴']] as const;

export default function DailyTasksScreen() {
  const { colors } = useAppTheme(); const styles = makeStyles(colors); const router = useRouter(); const queryClient = useQueryClient(); const { date } = useDayStore();
  const [title, setTitle] = useState(''); const [duration, setDuration] = useState('30'); const [scheduleMode, setScheduleMode] = useState<ScheduleMode>('specific'); const [time, setTime] = useState(''); const [anchor, setAnchor] = useState('after_fajr'); const [editing, setEditing] = useState<Task | null>(null);
  const { data: tasks = [], isLoading } = useQuery({ queryKey: ['tasks-today', date], queryFn: () => tasksApi.getToday(date).then(r => r.data.data as Task[]) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['tasks-today'] });
  const reset = () => { setTitle(''); setDuration('30'); setTime(''); setAnchor('after_fajr'); setScheduleMode('specific'); setEditing(null); };
  const save = useMutation({ mutationFn: async () => {
    const minutes = Number(duration); if (!title.trim() || !Number.isInteger(minutes) || minutes < 1 || minutes > 1440) throw new Error('INVALID');
    if (scheduleMode === 'specific' && !/^\d{2}:\d{2}$/.test(time)) throw new Error('TIME');
    const data = { title: title.trim(), duration: minutes, ...(scheduleMode === 'specific' ? { start: time } : { anchor }) };
    if (editing) await tasksApi.update(editing._id, data); else await tasksApi.createDaily({ ...data, date });
  }, onSuccess: () => { refresh(); reset(); }, onError: (error: Error) => Alert.alert('تحقق من البيانات', error.message === 'TIME' ? 'اكتب الوقت بصيغة HH:MM، مثل 14:30.' : 'اكتب عنوانًا ومدة صحيحة.') });
  const remove = useMutation({ mutationFn: (id: string) => tasksApi.delete(id), onSuccess: refresh });
  const beginEdit = (task: Task) => { setEditing(task); setTitle(task.title); setDuration(String(task.duration)); const prayer = task.anchor && task.anchor !== 'flexible'; setScheduleMode(prayer ? 'prayer' : 'specific'); setAnchor(prayer ? task.anchor! : 'after_fajr'); setTime(task.scheduledStart ? new Date(task.scheduledStart).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false }) : ''); };
  const confirmDelete = (task: Task) => Alert.alert('حذف المهمة؟', `سيتم حذف «${task.title}».`, [{ text: 'إلغاء', style: 'cancel' }, { text: 'حذف', style: 'destructive', onPress: () => remove.mutate(task._id) }]);
  return <SafeAreaView style={styles.container} edges={['top']}><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><Text style={styles.back}>← رجوع</Text></TouchableOpacity><View><Text style={styles.title}>مهام اليوم</Text><Text style={styles.subtitle}>{editing ? 'تعديل المهمة' : 'أضف وأدر مهامك'}</Text></View></View><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.card}><Text style={styles.cardTitle}>{editing ? 'تعديل المهمة' : 'مهمة جديدة'}</Text><Field label="العنوان" value={title} onChangeText={setTitle} styles={styles} placeholder="مثال: مراجعة المحاضرة" /><Field label="المدة بالدقائق" value={duration} onChangeText={setDuration} styles={styles} keyboardType="number-pad" placeholder="30" /><Text style={styles.label}>كيف تحدد وقتها؟</Text><View style={styles.options}><Chip label="🕐 وقت محدد" active={scheduleMode === 'specific'} onPress={() => setScheduleMode('specific')} styles={styles} /><Chip label="🕌 وقت صلاة" active={scheduleMode === 'prayer'} onPress={() => setScheduleMode('prayer')} styles={styles} /></View>{scheduleMode === 'specific' ? <Field label="الوقت (HH:MM)" value={time} onChangeText={setTime} styles={styles} keyboardType="numbers-and-punctuation" placeholder="14:30" /> : <><Text style={styles.label}>اختر وقت الصلاة</Text><View style={styles.options}>{PRAYERS.map(([value, label]) => <Chip key={value} label={label} active={anchor === value} onPress={() => setAnchor(value)} styles={styles} />)}</View></>}<View style={styles.formActions}>{editing && <TouchableOpacity style={styles.cancel} onPress={reset}><Text style={styles.cancelText}>إلغاء</Text></TouchableOpacity>}<TouchableOpacity style={styles.save} onPress={() => save.mutate()} disabled={save.isPending}>{save.isPending ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveText}>{editing ? 'حفظ التعديلات' : 'إضافة المهمة'}</Text>}</TouchableOpacity></View></View>
    <Text style={styles.sectionTitle}>مهام اليوم الحالية</Text>{isLoading && <ActivityIndicator color={colors.primary} />}{!isLoading && tasks.length === 0 && <Text style={styles.empty}>لا توجد مهام اليوم بعد.</Text>}{tasks.map(task => <View key={task._id} style={styles.taskCard}><View><Text style={styles.taskTitle}>{task.title}</Text><Text style={styles.meta}>{task.duration} دقيقة · {task.anchor && task.anchor !== 'flexible' ? prayerLabel(task.anchor) : task.scheduledStart ? new Date(task.scheduledStart).toLocaleTimeString('ar-EG', { hour: '2-digit', minute: '2-digit' }) : 'بدون وقت'}</Text></View><View style={styles.taskActions}><TouchableOpacity onPress={() => beginEdit(task)}><Text style={styles.edit}>تعديل</Text></TouchableOpacity><TouchableOpacity onPress={() => confirmDelete(task)}><Text style={styles.delete}>حذف</Text></TouchableOpacity></View></View>)}</ScrollView></SafeAreaView>;
}
function Field({ label, styles, ...props }: any) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} textAlign="right" placeholderTextColor="#8A9893" /></View>; }
function Chip({ label, active, onPress, styles }: any) { return <TouchableOpacity onPress={onPress} style={[styles.chip, active && styles.chipActive]}><Text style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text></TouchableOpacity>; }
function prayerLabel(anchor: string) { return PRAYERS.find(([value]) => value === anchor)?.[1] || anchor; }
const makeStyles = (c: ReturnType<typeof useAppTheme>['colors']) => StyleSheet.create({ container:{flex:1,backgroundColor:c.background},header:{backgroundColor:c.surface,padding:Spacing.base,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderBottomColor:c.border},back:{color:c.primary,fontWeight:'700'},title:{color:c.text,fontSize:Typography.size.xl,fontWeight:'800',textAlign:'right'},subtitle:{color:c.textSecondary,fontSize:Typography.size.xs,textAlign:'right'},content:{padding:Spacing.base,paddingBottom:90},card:{backgroundColor:c.surface,borderRadius:BorderRadius.lg,padding:Spacing.base,borderWidth:1,borderColor:c.border},cardTitle:{color:c.text,fontSize:Typography.size.md,fontWeight:'800',textAlign:'right'},field:{marginTop:Spacing.md},label:{color:c.text,fontSize:Typography.size.sm,fontWeight:'700',textAlign:'right',marginTop:Spacing.md,marginBottom:Spacing.xs},input:{backgroundColor:c.surfaceMuted,borderWidth:1,borderColor:c.border,color:c.text,borderRadius:BorderRadius.md,padding:Spacing.md,fontSize:Typography.size.base},options:{flexDirection:'row-reverse',flexWrap:'wrap',gap:Spacing.sm},chip:{paddingHorizontal:Spacing.sm,paddingVertical:Spacing.sm,borderWidth:1,borderColor:c.border,borderRadius:BorderRadius.full,backgroundColor:c.surfaceMuted},chipActive:{backgroundColor:c.primary,borderColor:c.primary},chipText:{color:c.textSecondary,fontSize:Typography.size.xs},chipTextActive:{color:'#fff',fontWeight:'700'},formActions:{flexDirection:'row-reverse',gap:Spacing.sm,marginTop:Spacing.xl},save:{flex:1,backgroundColor:c.primary,padding:Spacing.base,alignItems:'center',borderRadius:BorderRadius.md},saveText:{color:'#fff',fontWeight:'800'},cancel:{padding:Spacing.base,borderWidth:1,borderColor:c.border,borderRadius:BorderRadius.md},cancelText:{color:c.textSecondary,fontWeight:'700'},sectionTitle:{color:c.text,fontSize:Typography.size.md,fontWeight:'800',textAlign:'right',marginTop:Spacing.xl,marginBottom:Spacing.sm},empty:{color:c.textSecondary,textAlign:'right'},taskCard:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:BorderRadius.md,padding:Spacing.md,marginBottom:Spacing.sm,flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},taskTitle:{color:c.text,fontWeight:'700',textAlign:'right'},meta:{color:c.textSecondary,fontSize:Typography.size.xs,textAlign:'right',marginTop:3},taskActions:{flexDirection:'row-reverse',gap:Spacing.md},edit:{color:c.primary,fontWeight:'700'},delete:{color:c.error,fontWeight:'700'} });
