import React, { useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { remindersApi, tasksApi } from '../src/services/endpoints';
import { useDayStore } from '../src/stores/useDayStore';
import { BorderRadius, Spacing, Typography } from '../src/constants/theme';
import { useAppTheme } from '../src/theme/ThemeProvider';

type Mode = 'task' | 'reminder';
type Task = { _id: string; title: string; duration: number; scheduledStart?: string };
type Reminder = { _id: string; title: string; date: string; time?: string; duration: number };

export default function DailyTasksScreen() {
  const { colors } = useAppTheme(); const styles = makeStyles(colors); const router = useRouter(); const queryClient = useQueryClient(); const { date } = useDayStore();
  const [mode, setMode] = useState<Mode>('task'); const [title, setTitle] = useState(''); const [duration, setDuration] = useState('30'); const [time, setTime] = useState(''); const [reminderDate, setReminderDate] = useState(''); const [editing, setEditing] = useState<Task | null>(null);
  const { data: tasks = [], isLoading } = useQuery({ queryKey: ['tasks-today', date], queryFn: () => tasksApi.getToday(date).then(r => r.data.data as Task[]) });
  const { data: reminders = [] } = useQuery({ queryKey: ['reminders'], queryFn: () => remindersApi.list().then(r => r.data.data as Reminder[]) });
  const refreshTasks = () => queryClient.invalidateQueries({ queryKey: ['tasks-today'] }); const refreshReminders = () => queryClient.invalidateQueries({ queryKey: ['reminders'] });
  const reset = () => { setTitle(''); setDuration('30'); setTime(''); setReminderDate(''); setEditing(null); };
  const save = useMutation({ mutationFn: async () => {
    const minutes = Number(duration); if (!title.trim() || !Number.isInteger(minutes) || minutes < 1 || minutes > 1440) throw new Error('INVALID');
    if (!/^\d{2}:\d{2}$/.test(time)) throw new Error('TIME');
    if (mode === 'reminder') { if (!/^\d{4}-\d{2}-\d{2}$/.test(reminderDate)) throw new Error('DATE'); await remindersApi.create({ title: title.trim(), date: reminderDate, time, duration: minutes }); return; }
    const data = { title: title.trim(), duration: minutes, start: time };
    if (editing) await tasksApi.update(editing._id, data); else await tasksApi.createDaily({ ...data, date });
  }, onSuccess: () => { mode === 'reminder' ? refreshReminders() : refreshTasks(); reset(); }, onError: (error: Error) => Alert.alert('تحقق من البيانات', error.message === 'TIME' ? 'اكتب الوقت بصيغة HH:MM، مثل 14:30.' : error.message === 'DATE' ? 'اكتب تاريخ التذكير بصيغة YYYY-MM-DD.' : 'اكتب عنوانًا ومدة صحيحة.') });
  const removeTask = useMutation({ mutationFn: (id: string) => tasksApi.delete(id), onSuccess: refreshTasks }); const removeReminder = useMutation({ mutationFn: (id: string) => remindersApi.delete(id), onSuccess: refreshReminders });
  const beginEdit = (task: Task) => { setMode('task'); setEditing(task); setTitle(task.title); setDuration(String(task.duration)); setTime(task.scheduledStart ? new Date(task.scheduledStart).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false }) : ''); };
  const confirmDelete = (kind: 'task' | 'reminder', id: string, itemTitle: string) => Alert.alert('حذف؟', `سيتم حذف «${itemTitle}».`, [{ text: 'إلغاء', style: 'cancel' }, { text: 'حذف', style: 'destructive', onPress: () => kind === 'task' ? removeTask.mutate(id) : removeReminder.mutate(id) }]);
  return <SafeAreaView style={styles.container} edges={['top']}><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><Text style={styles.back}>← رجوع</Text></TouchableOpacity><View><Text style={styles.title}>مهام وتذكيرات</Text><Text style={styles.subtitle}>{editing ? 'تعديل المهمة' : 'أضف وأدر مهامك'}</Text></View></View><ScrollView contentContainerStyle={styles.content}>
    {!editing && <View style={styles.tabs}><Tab label="✓ مهمة اليوم" active={mode === 'task'} onPress={() => { setMode('task'); reset(); }} styles={styles} /><Tab label="🔔 تذكير" active={mode === 'reminder'} onPress={() => { setMode('reminder'); reset(); }} styles={styles} /></View>}
    <View style={styles.card}><Text style={styles.cardTitle}>{editing ? 'تعديل المهمة' : mode === 'task' ? 'مهمة جديدة لليوم' : 'تذكير جديد'}</Text><Field label="العنوان" value={title} onChangeText={setTitle} styles={styles} colors={colors} placeholder="مثال: مراجعة المحاضرة" /><Field label="المدة بالدقائق" value={duration} onChangeText={setDuration} styles={styles} colors={colors} keyboardType="number-pad" placeholder="30" />{mode === 'reminder' && <Field label="تاريخ التذكير (YYYY-MM-DD)" value={reminderDate} onChangeText={setReminderDate} styles={styles} colors={colors} keyboardType="numbers-and-punctuation" placeholder="2026-12-31" />}<Field label="الوقت الذي تحدده (HH:MM)" value={time} onChangeText={setTime} styles={styles} colors={colors} keyboardType="numbers-and-punctuation" placeholder="14:30" /><View style={styles.formActions}>{editing && <TouchableOpacity style={styles.cancel} onPress={reset}><Text style={styles.cancelText}>إلغاء</Text></TouchableOpacity>}<TouchableOpacity style={styles.save} onPress={() => save.mutate()} disabled={save.isPending}>{save.isPending ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveText}>{editing ? 'حفظ التعديلات' : mode === 'task' ? 'إضافة المهمة' : 'حفظ التذكير'}</Text>}</TouchableOpacity></View></View>
    <Text style={styles.sectionTitle}>مهام اليوم الحالية</Text>{isLoading && <ActivityIndicator color={colors.primary} />}{!isLoading && tasks.length === 0 && <Text style={styles.empty}>لا توجد مهام اليوم بعد.</Text>}{tasks.map(task => <Row key={task._id} title={task.title} detail={`${task.duration} دقيقة · ${task.scheduledStart ? new Date(task.scheduledStart).toLocaleTimeString('ar-EG', { hour: '2-digit', minute: '2-digit' }) : 'بدون وقت'}`} onEdit={() => beginEdit(task)} onDelete={() => confirmDelete('task', task._id, task.title)} styles={styles} />)}
    <Text style={styles.sectionTitle}>التذكيرات القادمة</Text>{reminders.length === 0 && <Text style={styles.empty}>لا توجد تذكيرات محفوظة.</Text>}{reminders.map(reminder => <Row key={reminder._id} title={reminder.title} detail={`${reminder.date} · ${reminder.time || 'بدون وقت'} · ${reminder.duration} دقيقة`} onDelete={() => confirmDelete('reminder', reminder._id, reminder.title)} styles={styles} />)}</ScrollView></SafeAreaView>;
}
function Field({ label, styles, colors, ...props }: any) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} textAlign="right" placeholderTextColor={colors?.textMuted || "#8A9893"} /></View>; }
function Tab({ label, active, onPress, styles }: any) { return <TouchableOpacity onPress={onPress} style={[styles.tab, active && styles.tabActive]}><Text style={[styles.tabText, active && styles.tabTextActive]}>{label}</Text></TouchableOpacity>; }
function Row({ title, detail, onEdit, onDelete, styles }: any) { return <View style={styles.row}><View><Text style={styles.rowTitle}>{title}</Text><Text style={styles.meta}>{detail}</Text></View><View style={styles.actions}>{onEdit && <TouchableOpacity onPress={onEdit}><Text style={styles.edit}>تعديل</Text></TouchableOpacity>}<TouchableOpacity onPress={onDelete}><Text style={styles.delete}>حذف</Text></TouchableOpacity></View></View>; }
const makeStyles = (c: ReturnType<typeof useAppTheme>['colors']) => StyleSheet.create({ container:{flex:1,backgroundColor:c.background},header:{backgroundColor:c.surface,padding:Spacing.base,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderBottomColor:c.border},back:{color:c.primary,fontWeight:'700'},title:{color:c.text,fontSize:Typography.size.xl,fontWeight:'800',textAlign:'right'},subtitle:{color:c.textSecondary,fontSize:Typography.size.xs,textAlign:'right'},content:{padding:Spacing.base,paddingBottom:90},tabs:{flexDirection:'row-reverse',gap:Spacing.sm,marginBottom:Spacing.base},tab:{flex:1,padding:Spacing.md,alignItems:'center',backgroundColor:c.surfaceMuted,borderRadius:BorderRadius.md,borderWidth:1,borderColor:c.border},tabActive:{backgroundColor:c.primary,borderColor:c.primary},tabText:{color:c.textSecondary,fontWeight:'700'},tabTextActive:{color:'#fff'},card:{backgroundColor:c.surface,borderRadius:BorderRadius.lg,padding:Spacing.base,borderWidth:1,borderColor:c.border},cardTitle:{color:c.text,fontSize:Typography.size.md,fontWeight:'800',textAlign:'right'},field:{marginTop:Spacing.md},label:{color:c.text,fontSize:Typography.size.sm,fontWeight:'700',textAlign:'right',marginBottom:Spacing.xs},input:{backgroundColor:c.surfaceMuted,borderWidth:1,borderColor:c.border,color:c.text,borderRadius:BorderRadius.md,padding:Spacing.md,fontSize:Typography.size.base},formActions:{flexDirection:'row-reverse',gap:Spacing.sm,marginTop:Spacing.xl},save:{flex:1,backgroundColor:c.primary,padding:Spacing.base,alignItems:'center',borderRadius:BorderRadius.md},saveText:{color:'#fff',fontWeight:'800'},cancel:{padding:Spacing.base,borderWidth:1,borderColor:c.border,borderRadius:BorderRadius.md},cancelText:{color:c.textSecondary,fontWeight:'700'},sectionTitle:{color:c.text,fontSize:Typography.size.md,fontWeight:'800',textAlign:'right',marginTop:Spacing.xl,marginBottom:Spacing.sm},empty:{color:c.textSecondary,textAlign:'right'},row:{backgroundColor:c.surface,borderWidth:1,borderColor:c.border,borderRadius:BorderRadius.md,padding:Spacing.md,marginBottom:Spacing.sm,flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},rowTitle:{color:c.text,fontWeight:'700',textAlign:'right'},meta:{color:c.textSecondary,fontSize:Typography.size.xs,textAlign:'right',marginTop:3},actions:{flexDirection:'row-reverse',gap:Spacing.md},edit:{color:c.primary,fontWeight:'700'},delete:{color:c.error,fontWeight:'700'} });
