import React, { useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { goalsApi, remindersApi, routinesApi, tasksApi } from '../src/services/endpoints';
import { useDayStore } from '../src/stores/useDayStore';
import { BorderRadius, Spacing, Typography } from '../src/constants/theme';
import { useAppTheme } from '../src/theme/ThemeProvider';
import axios from 'axios';

type Mode = 'today' | 'reminder';
interface Goal { _id: string; title: string; progress: number }

export default function DailyTasksScreen() {
  const { colors } = useAppTheme(); const styles: any = makeStyles(colors); const router = useRouter(); const queryClient = useQueryClient(); const { date } = useDayStore();
  const [mode, setMode] = useState<Mode>('today'); const [title, setTitle] = useState(''); const [time, setTime] = useState(''); const [duration, setDuration] = useState('30'); const [selectedGoal, setSelectedGoal] = useState(''); const [contribution, setContribution] = useState('0'); const [reminderDate, setReminderDate] = useState('');
  const { data: todayTasks = [] } = useQuery({ queryKey: ['tasks-today', date], queryFn: () => tasksApi.getToday(date).then(r => r.data.data) });
  const { data: routines = [] } = useQuery({ queryKey: ['routines'], queryFn: () => routinesApi.list().then(r => r.data.data) });
  const { data: goals = [] } = useQuery({ queryKey: ['goals', 'active'], queryFn: () => goalsApi.list({ status: 'active' }).then(r => r.data.data as Goal[]) });
  const { data: reminders = [] } = useQuery({ queryKey: ['reminders'], queryFn: () => remindersApi.list().then(r => r.data.data) });
  const save = useMutation({ mutationFn: () => {
    const cleanTitle = title.trim(); const minutes = Number(duration.trim()); const selectedDate = date || localDate();
    if (!cleanTitle) throw new Error('TITLE'); if (!Number.isInteger(minutes) || minutes < 1 || minutes > 1440) throw new Error('DURATION');
    if (mode === 'reminder') { if (!/^\d{4}-\d{2}-\d{2}$/.test(reminderDate.trim())) throw new Error('DATE'); return remindersApi.create({ title: cleanTitle, date: reminderDate.trim(), time: time.trim() || undefined, duration: minutes }); }
    const delta = Number(contribution); if (!Number.isFinite(delta) || delta < 0 || delta > 100) throw new Error('PROGRESS');
    return tasksApi.createDaily({ title: cleanTitle, date: selectedDate, duration: minutes, start: time.trim() || undefined, goalId: selectedGoal || undefined, goalProgressDelta: selectedGoal ? delta : 0 });
  }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['tasks-today'] }); queryClient.invalidateQueries({ queryKey: ['reminders'] }); setTitle(''); setTime(''); setDuration('30'); setContribution('0'); setSelectedGoal(''); Alert.alert('تم الحفظ', mode === 'today' ? 'المهمة ظهرت في مهام اليوم.' : 'سيتم إضافتها تلقائيًا عند بدء ذلك اليوم.'); }, onError: (e: unknown) => { const serverMessage = axios.isAxiosError(e) ? e.response?.data?.message : undefined; const message = e instanceof Error ? e.message : ''; Alert.alert('تعذر الحفظ', serverMessage || (message === 'TITLE' ? 'اكتب اسم المهمة أو التذكير.' : message === 'DURATION' ? 'اكتب مدة صحيحة بين 1 و1440 دقيقة.' : message === 'DATE' ? 'أدخل التاريخ مثل 2026-12-31.' : message === 'PROGRESS' ? 'نسبة التقدم بين 0 و100.' : 'حدث خطأ غير متوقع. حاول مرة أخرى.')); } });
  return <SafeAreaView style={styles.container} edges={['top']}><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><Text style={styles.back}>← رجوع</Text></TouchableOpacity><View><Text style={styles.title}>مهام اليوم</Text><Text style={styles.subtitle}>نظّم اليوم والتزاماتك القادمة</Text></View></View><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.switcher}>{(['today','reminder'] as Mode[]).map(item => <TouchableOpacity key={item} style={[styles.switch, mode === item && styles.switchActive]} onPress={() => setMode(item)}><Text style={[styles.switchText, mode === item && styles.switchTextActive]}>{item === 'today' ? '✓ أضف لليوم' : '🔔 تذكير مستقبلي'}</Text></TouchableOpacity>)}</View>
    <View style={styles.card}><Text style={styles.cardTitle}>{mode === 'today' ? 'مهمة مباشرة لليوم' : 'موعد أو تذكير'}</Text><Field styles={styles} label="العنوان" value={title} onChangeText={setTitle} placeholder={mode === 'today' ? 'مثال: مراجعة المحاضرة' : 'مثال: موعد الطبيب'} /><View style={styles.row}><Field styles={styles} label={mode === 'reminder' ? 'التاريخ (YYYY-MM-DD)' : 'الوقت (اختياري)'} value={mode === 'reminder' ? reminderDate : time} onChangeText={mode === 'reminder' ? setReminderDate : setTime} placeholder={mode === 'reminder' ? '2026-12-31' : '14:30'} /><Field styles={styles} label="المدة بالدقائق" value={duration} onChangeText={setDuration} placeholder="30" keyboardType="number-pad" /></View>{mode === 'reminder' && <Field styles={styles} label="الوقت (اختياري)" value={time} onChangeText={setTime} placeholder="14:30" />}{mode === 'today' && <><Text style={styles.label}>ربط بهدف (اختياري)</Text><View style={styles.options}><Choice styles={styles} active={!selectedGoal} label="بدون هدف" onPress={() => setSelectedGoal('')} />{goals.map(goal => <Choice key={goal._id} styles={styles} active={selectedGoal === goal._id} label={goal.title} onPress={() => setSelectedGoal(goal._id)} />)}</View>{selectedGoal ? <Field styles={styles} label="كم يضيف لإنجاز الهدف؟ (%)" value={contribution} onChangeText={setContribution} placeholder="مثال: 5" keyboardType="decimal-pad" /> : null}</>}<TouchableOpacity style={styles.save} onPress={() => save.mutate()} disabled={save.isPending}>{save.isPending ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveText}>{mode === 'today' ? 'إضافة لمهام اليوم' : 'حفظ التذكير'}</Text>}</TouchableOpacity></View>
    <Section styles={styles} title="مهام اليوم الحالية" empty="لا توجد مهام اليوم بعد.">{todayTasks.map((task: any) => <Item key={task._id} styles={styles} title={task.title} detail={`${task.duration} دقيقة${task.scheduledStart ? ` · ${new Date(task.scheduledStart).toLocaleTimeString('ar-EG', {hour:'2-digit', minute:'2-digit'})}` : ''}`} />)}</Section>
    <Section styles={styles} title="مهام اليوم التالي المحفوظة" empty="أضف روتينًا من صفحة «أضف جديد». ">{routines.filter((r: any) => r.enabled).map((routine: any) => <Item key={routine._id} styles={styles} title={routine.title} detail={`${routine.duration} دقيقة · ستُنشأ عند بدء يوم جديد${routine.goalProgressContribution ? ` · يزيد الهدف ${routine.goalProgressContribution}%` : ''}`} />)}</Section>
    <Section styles={styles} title="التذكيرات القادمة" empty="لا توجد تذكيرات محفوظة.">{reminders.map((reminder: any) => <Item key={reminder._id} styles={styles} title={reminder.title} detail={`${reminder.date}${reminder.time ? ` · ${reminder.time}` : ''} · ${reminder.duration} دقيقة`} />)}</Section>
  </ScrollView></SafeAreaView>;
}
function Field({ styles, label, ...props }: any) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} placeholderTextColor="#8A9893" textAlign="right" autoCapitalize="none" /></View>; }
function localDate(): string { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); }
function Choice({ styles, active, label, onPress }: any) { return <TouchableOpacity onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><Text numberOfLines={1} style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></TouchableOpacity>; }
function Item({ styles, title, detail }: any) { return <View style={styles.item}><Text style={styles.itemTitle}>{title}</Text><Text style={styles.itemDetail}>{detail}</Text></View>; }
function Section({ styles, title, empty, children }: any) { const has = Array.isArray(children) ? children.length > 0 : !!children; return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{has ? children : <Text style={styles.empty}>{empty}</Text>}</View>; }
const makeStyles = (c: ReturnType<typeof useAppTheme>['colors']): any => StyleSheet.create({ container:{flex:1,backgroundColor:c.background},header:{backgroundColor:c.surface,padding:Spacing.base,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderBottomColor:c.border},back:{color:c.primary,fontWeight:'700'},title:{color:c.text,fontSize:Typography.size.xl,fontWeight:'800',textAlign:'right'},subtitle:{color:c.textSecondary,fontSize:Typography.size.xs,textAlign:'right'},content:{padding:Spacing.base,paddingBottom:90},switcher:{flexDirection:'row-reverse',gap:Spacing.sm,marginBottom:Spacing.base},switch:{flex:1,padding:Spacing.md,alignItems:'center',backgroundColor:c.surfaceMuted,borderRadius:BorderRadius.md,borderWidth:1,borderColor:c.border},switchActive:{backgroundColor:c.primary,borderColor:c.primary},switchText:{color:c.textSecondary,fontWeight:'700'},switchTextActive:{color:'#fff'},card:{backgroundColor:c.surface,borderRadius:BorderRadius.lg,padding:Spacing.base,borderWidth:1,borderColor:c.border},cardTitle:{color:c.text,fontSize:Typography.size.md,fontWeight:'800',textAlign:'right'},field:{marginTop:Spacing.md,flex:1},label:{color:c.text,fontSize:Typography.size.sm,fontWeight:'700',textAlign:'right',marginBottom:Spacing.xs},input:{backgroundColor:c.surfaceMuted,borderWidth:1,borderColor:c.border,color:c.text,borderRadius:BorderRadius.md,padding:Spacing.md,fontSize:Typography.size.base},row:{flexDirection:'row-reverse',gap:Spacing.sm},options:{flexDirection:'row-reverse',flexWrap:'wrap',gap:Spacing.sm},choice:{maxWidth:'100%',paddingHorizontal:Spacing.sm,paddingVertical:Spacing.sm,borderWidth:1,borderColor:c.border,borderRadius:BorderRadius.full,backgroundColor:c.surfaceMuted},choiceActive:{backgroundColor:c.primary,borderColor:c.primary},choiceText:{color:c.textSecondary,fontSize:Typography.size.xs},choiceTextActive:{color:'#fff',fontWeight:'700'},save:{backgroundColor:c.primary,padding:Spacing.base,alignItems:'center',borderRadius:BorderRadius.md,marginTop:Spacing.xl},saveText:{color:'#fff',fontSize:Typography.size.base,fontWeight:'800'},section:{marginTop:Spacing.xl},sectionTitle:{color:c.text,fontSize:Typography.size.md,fontWeight:'800',textAlign:'right',marginBottom:Spacing.sm},item:{backgroundColor:c.surface,padding:Spacing.md,borderRadius:BorderRadius.md,marginBottom:Spacing.sm,borderWidth:1,borderColor:c.border},itemTitle:{color:c.text,fontWeight:'700',textAlign:'right'},itemDetail:{color:c.textSecondary,fontSize:Typography.size.xs,textAlign:'right',marginTop:3},empty:{backgroundColor:c.surfaceMuted,color:c.textSecondary,padding:Spacing.base,borderRadius:BorderRadius.md,textAlign:'right'} });
